// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://canofbjfgivytxcpybvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhbm9mYmpmZ2l2eXR4Y3B5YnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDk4MDksImV4cCI6MjA1ODcyNTgwOX0.1roFWaphl0zVE0f1Jb1Ul34DHCidIaw4kiYt0IwVCUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);