
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcdqflrolbjykkiamqvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZHFmbHJvbGJqeWtraWFtcXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjQ4NTQsImV4cCI6MjA2NDY0MDg1NH0.IgN1pEw9al9V0-UT9U1aLB013IsQUC8aRXXRXjVOT8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
